In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Col1': [100, 200, 300],
    'Col2': [400, 500, 600],
    'Col3': [700, 800, 900]
}, index=['fila1', 'fila2', 'fila3'])

df

       Col1  Col2  Col3
fila1   100   400   700
fila2   200   500   800
fila3   300   600   900

In [3]:
df.loc['fila1']

Col1    100
Col2    400
Col3    700
Name: fila1, dtype: int64

In [4]:
type(df.loc['fila1'])

pandas.core.series.Series

In [5]:
df.loc[['fila1', 'fila3']]

       Col1  Col2  Col3
fila1   100   400   700
fila3   300   600   900

In [6]:
type(df.loc[['fila1', 'fila3']])

pandas.core.frame.DataFrame

In [ ]:
df.loc['fila2':'fila3'] # loc en este si es inclusivo

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [ ]:
df.loc[[False, True, False]] # True para fila2

       Col1  Col2  Col3
fila2   200   500   800

In [9]:
df.loc[df['Col1'] > 150]

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [12]:
df.loc[:, ['Col1', 'Col2']]

       Col1  Col2
fila1   100   400
fila2   200   500
fila3   300   600

In [13]:
df.iloc[0]

Col1    100
Col2    400
Col3    700
Name: fila1, dtype: int64

In [14]:
df.iloc[:, [0,1]]

       Col1  Col2
fila1   100   400
fila2   200   500
fila3   300   600

In [17]:
df.iloc[1:3] # posiciones 1 y 2, el 3 no se incluye

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

Acceder a Elementos del DataFrame con 'Ioc' e 'iloc' 1
Utiliza loc para seleccionar los datos de la fila denominada "fila2" en el siguiente DataFrame df.  Tu resultado debe ser una Serie de Pandas llamada resultado

df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carmen'],
    'Edad': [25, 30, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}, index=['fila1', 'fila2', 'fila3'])

In [24]:
import pandas as pd 
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carmen'],
    'Edad': [25, 30, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}, index=['fila1', 'fila2', 'fila3'])
resultado = df.loc["fila2"]

In [26]:
type(resultado)

pandas.core.series.Series

Acceder a Elementos del DataFrame con 'Ioc' e 'iloc' 2
Utiliza loc para seleccionar las filas "fila1" y "fila3" del DataFrame df. Tu resultado debe ser un DataFrame nombrado resultado.



df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carmen'],
    'Edad': [25, 30, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}, index=['fila1', 'fila2', 'fila3'])

In [28]:
import pandas as pd
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carmen'],
    'Edad': [25, 30, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}, index=['fila1', 'fila2', 'fila3'])

resultado = df.loc[["fila1", "fila3"]]
resultado

       Nombre  Edad    Ciudad
fila1     Ana    25    Madrid
fila3  Carmen    22  Valencia

Acceder a Elementos del DataFrame con 'Ioc' e 'iloc' 3
Utiliza iloc para seleccionar las primeras dos filas y las últimas dos columnas del siguiente DataFrame df. El resultado debe ser un DataFrame llamado resultado



df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
})

In [30]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
})

resultado = df.iloc[0:2, 2:4]
resultado

    C   D
0   9  13
1  10  14