In [1]:
import pandas as pd

df1 = pd.DataFrame({'Salario': [30000, 45000, 38000],
                    'Antigüedad': [9, 13, 12]},
                   index=[1, 2, 3])
df2 = pd.DataFrame({'Ciudad': ['Madrid', 'Barcelona', 'Valencia'],
                    'Jerarquía': ['Baja', 'Alta', 'Media']},
                   index=[1, 2, 4])

In [2]:
df1

   Salario  Antigüedad
1    30000           9
2    45000          13
3    38000          12

In [3]:
df2

      Ciudad Jerarquía
1     Madrid      Baja
2  Barcelona      Alta
4   Valencia     Media

In [4]:
df_unido= df1.join(df2)
df_unido

   Salario  Antigüedad     Ciudad Jerarquía
1    30000           9     Madrid      Baja
2    45000          13  Barcelona      Alta
3    38000          12        NaN       NaN

In [5]:
df_unido= df1.join(df2, how='inner')
df_unido

   Salario  Antigüedad     Ciudad Jerarquía
1    30000           9     Madrid      Baja
2    45000          13  Barcelona      Alta

In [6]:
df_unido= df1.join(df2, how='right')
df_unido

   Salario  Antigüedad     Ciudad Jerarquía
1  30000.0         9.0     Madrid      Baja
2  45000.0        13.0  Barcelona      Alta
4      NaN         NaN   Valencia     Media

In [7]:
df_unido= df1.join(df2, how='outer')
df_unido

   Salario  Antigüedad     Ciudad Jerarquía
1  30000.0         9.0     Madrid      Baja
2  45000.0        13.0  Barcelona      Alta
3  38000.0        12.0        NaN       NaN
4      NaN         NaN   Valencia     Media

Combinar DataFrames en Pandas con join() 1
Dados dos DataFrames, df_a y df_b. df_a

# Creación del DataFrame df_a
df_a = pd.DataFrame({
    'id': [1, 2, 3],
    'Nombre': ['Ana', 'Beto', 'Carla']
})
df_a.set_index('id', inplace=True)
 
# Creación del DataFrame df_b
df_b = pd.DataFrame({
    'id': [1, 2, 3],
    'Edad': [25, 30, 35]
})
df_b.set_index('id', inplace=True)
Utiliza el método join() para combinar df_a y df_b en un nuevo DataFrame llamado df_combinado, usando el argumento por defecto de how.

In [8]:
import pandas as pd


# Creación del DataFrame df_a
df_a = pd.DataFrame({
    'id': [1, 2, 3],
    'Nombre': ['Ana', 'Beto', 'Carla']
})
df_a.set_index('id', inplace=True)

# Creación del DataFrame df_b
df_b = pd.DataFrame({
    'id': [1, 2, 3],
    'Edad': [25, 30, 35]
})
df_b.set_index('id', inplace=True)

df_combinado = df_a.join(df_b, how='inner')
df_combinado

   Nombre  Edad
id
1     Ana    25
2    Beto    30
3   Carla    35

Combinar DataFrames en Pandas con join() 2
Dado el DataFrame productos_df con columnas ProductoID, Nombre y Precio, y el DataFrame categorias_df con columnas CategoriaID y NombreCategoria



# Creamos los DataFrames de ejemplo
productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
}).set_index('ProductoID')
 
categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2],
    'NombreCategoria': ['Categoría 1', 'Categoría 2']
}).set_index('CategoriaID')


Donde ambos DataFrames están indexados por ProductoID y CategoriaID respectivamente, realiza una unión usando el método join() para combinar estos DataFrames en un nuevo DataFrames  nombrado: df_combinado basándote en sus índices, asegurándote de que todos los productos se muestren, independientemente de si tienen una categoría asignada o no.

Utiliza el método adecuado  para asegurar que todos los registros del DataFrame de la izquierda (productos_df en este caso) se incluyan en el DataFrame resultante df_combinado, independientemente de si tienen una correspondencia en el DataFrame de la derecha (categorias_df).

In [9]:
import pandas as pd
productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
}).set_index('ProductoID')

categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2],
    'NombreCategoria': ['Categoría 1', 'Categoría 2']
}).set_index('CategoriaID')

df_combinado = productos_df.join(categorias_df, how= 'left')
df_combinado

                Nombre  Precio NombreCategoria
ProductoID
1           Producto 1     100     Categoría 1
2           Producto 2     150     Categoría 2
3           Producto 3     200             NaN
4           Producto 4     250             NaN

Combinar DataFrames en Pandas con join() 3
Combinar DataFrames en Pandas con join() 3

En este ejercicio, trabajarás con dos DataFrames: productos_df y categorias_df.

productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
})
 
productos_df = productos_df.set_index('ProductoID')
 
categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2, 3],
    'NombreCategoria': ['Categoría 1', 'Categoría 2', 'Categoría 3']
}).set_index('CategoriaID')
Tu tarea es combinar estos DataFrames en un DataFrame llamado df_combinado de tal manera que se conserven todos los registros del DataFrame de productos_df, incluso si no tienen una categoría correspondiente en categorias_df. Para esto, debes utilizar el parámetro how="right" en el método join().

Instrucciones:

Combina los DataFrames productos_df y categorias_df utilizando el método join() y el parámetro how="right".

Asigna el resultado a un DataFrame llamado df_combinado.

Ejemplo de Salida Esperada:

In [11]:

productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
})

productos_df = productos_df.set_index('ProductoID')

categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2, 3],
    'NombreCategoria': ['Categoría 1', 'Categoría 2', 'Categoría 3']
}).set_index('CategoriaID')

df_combinado = categorias_df.join(productos_df, how='right')
df_combinado

           NombreCategoria      Nombre  Precio
ProductoID
1              Categoría 1  Producto 1     100
2              Categoría 2  Producto 2     150
3              Categoría 3  Producto 3     200
4                      NaN  Producto 4     250