In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'Nombre': ["Juan", "Gabriela", "Elena"], 'Edad': [23, 31, 21]})
df1

     Nombre  Edad
0      Juan    23
1  Gabriela    31
2     Elena    21

In [3]:
df2 = pd.DataFrame({'Nombre': ["Carmela", "Max", "Laura"], 'Edad': [34, 25, 29]})
df2

    Nombre  Edad
0  Carmela    34
1      Max    25
2    Laura    29

In [4]:
df_concatenado = pd.concat([df1, df2])
df_concatenado

     Nombre  Edad
0      Juan    23
1  Gabriela    31
2     Elena    21
0   Carmela    34
1       Max    25
2     Laura    29

In [5]:
df_concatenado2 = pd.concat([df1, df2], axis=1)
df_concatenado2

     Nombre  Edad   Nombre  Edad
0      Juan    23  Carmela    34
1  Gabriela    31      Max    25
2     Elena    21    Laura    29

In [6]:
df_concatenado = pd.concat([df1, df2], ignore_index= True) # ignora el indeice de cada tabla y lo continua segun la tabla concatenada
df_concatenado

     Nombre  Edad
0      Juan    23
1  Gabriela    31
2     Elena    21
3   Carmela    34
4       Max    25
5     Laura    29

In [7]:
df_concatenado = pd.concat([df1, df2], keys=['df1', 'df2']) # deifrenciar entre uno y otro dataframe
df_concatenado

         Nombre  Edad
df1 0      Juan    23
    1  Gabriela    31
    2     Elena    21
df2 0   Carmela    34
    1       Max    25
    2     Laura    29

In [8]:
df_concatenado = pd.concat([df1, df2], keys=['enero', 'febreo'])
df_concatenado

            Nombre  Edad
enero  0      Juan    23
       1  Gabriela    31
       2     Elena    21
febreo 0   Carmela    34
       1       Max    25
       2     Laura    29

Concatenar DataFrames en Pandas con concat 1
Tienes dos conjuntos de datos representados por los siguientes DataFrames ventas_enero y ventas_febrero, que contienen las ventas de diferentes productos en los meses de enero y febrero, respectivamente.

ventas_enero = pd.DataFrame({'Producto': ["Manzanas", "Bananas", "Naranjas"], 'Cantidad': [300, 200, 150]})
ventas_febrero = pd.DataFrame({'Producto': ["Manzanas", "Bananas", "Naranjas"], 'Cantidad': [350, 210, 170]})
Tu tarea es utilizar el método concat() para concatenar estos dos DataFrames verticalmente en un nuevo DataFrame llamado ventas_total. Asegúrate de ignorar los índices originales para que el índice del DataFrame resultante sea continuo.

In [9]:
ventas_enero = pd.DataFrame({'Producto': ["Manzanas", "Bananas", "Naranjas"], 'Cantidad': [300, 200, 150]})

ventas_febrero = pd.DataFrame({'Producto': ["Manzanas", "Bananas", "Naranjas"], 'Cantidad': [350, 210, 170]})

ventas_total = pd.concat([ventas_enero, ventas_febrero],ignore_index=True )
ventas_total

   Producto  Cantidad
0  Manzanas       300
1   Bananas       200
2  Naranjas       150
3  Manzanas       350
4   Bananas       210
5  Naranjas       170

Concatenar DataFrames en Pandas con concat 2
Considera los siguientes DataFrames datos_cliente y compras_cliente, que contienen información sobre los clientes y sus compras, respectivamente.

datos_cliente = pd.DataFrame({'Nombre': ["Ana", "Luis", "Marta"], 'Edad': [34, 45, 28]})
compras_cliente = pd.DataFrame({'Producto': ["Libro", "Lápiz", "Cuaderno"], 'Precio': [15.50, 0.50, 2.00]})
Utiliza el método concat() para unir estos dos DataFrames horizontalmente, formando un nuevo DataFrame llamado info_cliente. Asegúrate de que los índices se mantengan para que cada fila corresponda correctamente entre los dos DataFrames.

In [11]:
datos_cliente = pd.DataFrame({'Nombre': ["Ana", "Luis", "Marta"], 'Edad': [34, 45, 28]})
compras_cliente = pd.DataFrame({'Producto': ["Libro", "Lápiz", "Cuaderno"], 'Precio': [15.50, 0.50, 2.00]})

info_cliente = pd.concat([datos_cliente,compras_cliente ],axis=1 )
info_cliente

  Nombre  Edad  Producto  Precio
0    Ana    34     Libro    15.5
1   Luis    45     Lápiz     0.5
2  Marta    28  Cuaderno     2.0

Concatenar DataFrames en Pandas con concat 3
Dado los siguientes DataFrames que representan las ventas de dos tiendas diferentes en el mismo mes:

tienda_a = pd.DataFrame({'Producto': ["Manzanas", "Bananas"], 'Cantidad': [500, 300]})
tienda_b = pd.DataFrame({'Producto': ["Naranjas", "Peras"], 'Cantidad': [400, 250]})
Tu tarea es concatenar estos DataFrames verticalmente en un nuevo DataFrame llamado ventas_tienda, utilizando el parámetro keys para marcar cada bloque de datos con las etiquetas "Tienda A" y "Tienda B", respectivamente. Asegúrate de que el DataFrame resultante tenga un índice jerárquico que refleje estas claves.

In [14]:
tienda_a = pd.DataFrame({'Producto': ["Manzanas", "Bananas"], 'Cantidad': [500, 300]})
tienda_b = pd.DataFrame({'Producto': ["Naranjas", "Peras"], 'Cantidad': [400, 250]})
ventas_tienda = pd.concat([tienda_a, tienda_b], keys=["Tienda A","Tienda B"])
ventas_tienda

            Producto  Cantidad
Tienda A 0  Manzanas       500
         1   Bananas       300
Tienda B 0  Naranjas       400
         1     Peras       250