In [3]:
import pandas as pd

In [2]:
fechas = pd.Series(pd.date_range('20240101',periods=6))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [4]:
type(fechas[0])

pandas._libs.tslibs.timestamps.Timestamp

In [5]:
fechas = pd.Series(pd.date_range('20240101',periods=6, freq='D'))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [8]:
fechas = pd.Series(pd.date_range('20240101',periods=6, freq='YE'))
fechas

0   2024-12-31
1   2025-12-31
2   2026-12-31
3   2027-12-31
4   2028-12-31
5   2029-12-31
dtype: datetime64[ns]

In [10]:
fechas = pd.Series(pd.date_range('20240101',periods=6, freq='h'))
fechas

0   2024-01-01 00:00:00
1   2024-01-01 01:00:00
2   2024-01-01 02:00:00
3   2024-01-01 03:00:00
4   2024-01-01 04:00:00
5   2024-01-01 05:00:00
dtype: datetime64[ns]

In [11]:
fechas = pd.Series(pd.date_range('20240101',periods=6, freq='min'))
fechas

0   2024-01-01 00:00:00
1   2024-01-01 00:01:00
2   2024-01-01 00:02:00
3   2024-01-01 00:03:00
4   2024-01-01 00:04:00
5   2024-01-01 00:05:00
dtype: datetime64[ns]

In [13]:
fechas = pd.Series(pd.date_range('20240101',periods=6, freq='5D'))
fechas

0   2024-01-01
1   2024-01-06
2   2024-01-11
3   2024-01-16
4   2024-01-21
5   2024-01-26
dtype: datetime64[ns]

In [14]:
ruta = 'Mercado+de+Valores+España.csv'
df = pd.read_csv(ruta)
df.head(5)

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,02/01/2019,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,03/01/2019,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,04/01/2019,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,07/01/2019,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,08/01/2019,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409

In [15]:
type(df['Fecha'])

pandas.core.series.Series

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8575 entries, 0 to 8574
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Ticker      8575 non-null   object
 1   Fecha       8575 non-null   object
 2   Cierre      8575 non-null   float64
 3   Referencia  8575 non-null   float64
 4   Volumen     8575 non-null   int64
 5   Rotacion    8575 non-null   float64
 6   Ultimo      8575 non-null   float64
 7   Alto        8575 non-null   float64
 8   Bajo        8575 non-null   float64
 9   Promedio    8575 non-null   float64
dtypes: float64(7), int64(1), object(2)
memory usage: 670.1+ KB

In [19]:
df['Fecha']= pd.to_datetime(df['Fecha'], format ='%d/%m/%Y')
df

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,2019-01-02,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,2019-01-03,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,2019-01-04,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,2019-01-07,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,2019-01-08,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,2019-12-09,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,2019-12-10,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,2019-12-11,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,2019-12-12,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,2019-12-13,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [21]:
df['Fecha'][0]

Timestamp('2019-01-02 00:00:00')

In [22]:
type(df['Fecha'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [24]:
df['Fecha'][44].year

2019

In [25]:
df['Fecha'][44].month

3

In [27]:
df_mas_5_dias = df['Fecha'] + pd.Timedelta(days = 5)
df_mas_5_dias

0      2019-01-07
1      2019-01-08
2      2019-01-09
3      2019-01-12
4      2019-01-13
          ...
8570   2019-12-14
8571   2019-12-15
8572   2019-12-16
8573   2019-12-17
8574   2019-12-18
Name: Fecha, Length: 8575, dtype: datetime64[ns]

Datos Relacionados con el Tiempo en Pandas 1
Crea una serie temporal que represente todos los días desde el inicio del año 2024 hasta el septimo dia del mismo mes y año. Usa el método adecuado para generar esta serie y asígnala a una variable llamada primera_semana_2024

In [ ]:
import pandas as pd
primera_semana_2024 = pd.Series(pd.date_range('20240101', periods=7))

Datos Relacionados con el Tiempo en Pandas 2
Dada una lista de fechas en formato string ['2024-01-01', '2024-02-14', '2024-03-01'] en una columna fecha de una tabla llamada fechas.csv



Debes leer el archivo CSV 'fechas.csv' desde tu código para ello emplea el método adecuado.

Convierte estas fechas al formato datetime de Pandas con el siguiente formato dia/mes/año. Almacena este DataFrame en una variable nombrada df

In [ ]:
import pandas as pd
ruta = 'fechas.csv'
df = pd.read_csv(ruta)
df['fecha'] = pd.to_datetime(df['fecha']).dt.strftime('%d/%m/%Y')

atos Relacionados con el Tiempo en Pandas 3
Dada una lista de fechas en formato string ['01-01-2024', '14-02-2024', '01-03-2024'] en una columna fecha de una tabla llamada fechas.csv


Debes leer el archivo CSV 'fechas.csv' desde tu código para ello emplea el método adecuado.

Convierte estas fechas al formato datetime de Pandas. Con el siguiente formato dia/mes/año. Almacena este DataFrame en una variable nombrada df

Agrega cinco días a cada fecha.

In [11]:

dato =  {'fecha':['01-01-2024', '14-02-2024', '01-03-2024']}
df = pd.DataFrame(dato)
df['fecha'] = pd.to_datetime(df['fecha'],dayfirst=True)
df['fecha'] = df['fecha'] + pd.Timedelta(days = 5)
df['fecha'] = df['fecha'].dt.strftime('%d/%m/%Y')
df

        fecha
0  06/01/2024
1  19/02/2024
2  06/03/2024