In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'ID': [1, 2, 3],
                    'Nombre': ['Ana', 'Luis', 'Carlos']})
df2 = pd.DataFrame({'ID': [1, 2, 4],
                    'Edad': [25, 30, 22]})

In [3]:
df1

   ID  Nombre
0   1     Ana
1   2    Luis
2   3  Carlos

In [4]:
df2

   ID  Edad
0   1    25
1   2    30
2   4    22

In [6]:
df_combinado = pd.merge(df1, df2, on='ID', how='inner') # el qeu se pinga priemro es el que va a al izquierda
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30

In [ ]:
df_combinado = pd.merge(df1, df2, on='ID', how='outer' ) # el qeu se pinga priemro es el que va a al izquierda
df_combinado # NaN para los datos faltantes

   ID  Nombre  Edad
0   1     Ana  25.0
1   2    Luis  30.0
2   3  Carlos   NaN
3   4     NaN  22.0

In [8]:
df_combinado = pd.merge(df1, df2, on='ID', how='left' ) 
df_combinado

   ID  Nombre  Edad
0   1     Ana  25.0
1   2    Luis  30.0
2   3  Carlos   NaN

In [9]:
df_combinado = pd.merge(df1, df2, on='ID', how='right' ) 
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30
2   4    NaN    22

In [10]:
df_indexado = pd.merge(df1, df2, left_index=True, right_index=True ) 
df_indexado

   ID_x  Nombre  ID_y  Edad
0     1     Ana     1    25
1     2    Luis     2    30
2     3  Carlos     4    22

Fusionar DataFrames con merge 1
Tienes dos DataFrames, libros y autores, que necesitas fusionar.

Estos DataFrames se definen de la siguiente manera:

libros = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'titulo': ['El Quijote', 'La Odisea', 'Cien Años de Soledad', 'El Principito']
})
 
autores = pd.DataFrame({
    'ID': [1, 2, 3, 5],
    'nombre': ['Miguel de Cervantes', 'Homero', 'Gabriel García Márquez', 'J.K. Rowling']
})
El objetivo es fusionar libros con autores para obtener un DataFrame que contenga toda la información disponible, asociando cada libro con su autor correspondiente. Debes nombrar el DataFrame fusionado como: libros_autores

Utiliza el método de fusión adecuado para asegurar que no se pierda ningún libro o autor, incluso si no hay una correspondencia directa entre ellos. El resultado debe tener NaN donde no haya información disponible.

In [11]:
import pandas as pd

libros = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'titulo': ['El Quijote', 'La Odisea', 'Cien Años de Soledad', 'El Principito']
})

autores = pd.DataFrame({
    'ID': [1, 2, 3, 5],
    'nombre': ['Miguel de Cervantes', 'Homero', 'Gabriel García Márquez', 'J.K. Rowling']
})

libros_autores = pd.merge(libros, autores, on = 'ID', how= 'outer'  )
libros_autores

   ID                titulo                  nombre
0   1            El Quijote     Miguel de Cervantes
1   2             La Odisea                  Homero
2   3  Cien Años de Soledad  Gabriel García Márquez
3   4         El Principito                     NaN
4   5                   NaN            J.K. Rowling


Fusionar DataFrames con merge 2
Imagina que estás trabajando con dos conjuntos de datos: uno que contiene información sobre cursos en línea ofrecidos (cursos) y otro que contiene información sobre las inscripciones a estos cursos (inscripciones).

Los DataFrames se definen de la siguiente manera:

cursos = pd.DataFrame({
    'curso_id': [101, 102, 103],
    'nombre_curso': ['Introducción a Python', 'Data Science con Python', 'Machine Learning Avanzado']
})
 
inscripciones = pd.DataFrame({
    'curso_id': [102, 102, 101, 104],
    'fecha_inscripcion': ['2023-01-15', '2023-02-01', '2023-01-20', '2023-03-05']
})
Tu tarea es fusionar cursos con inscripciones (en un DataFrame llamado: cursos_inscripciones) de tal manera que el resultado final incluya todos los registros de inscripciones, completándolos con la información disponible en cursos.

Utiliza el método de fusión adecuado para garantizar que no se pierda ninguna inscripción, incluso si el curso correspondiente no está listado en el DataFrame cursos. Es importante que el DataFrame resultante cursos_inscripciones muestre claramente qué inscripciones no tienen un curso correspondiente, rellenando esos espacios con NaN.

In [14]:


cursos = pd.DataFrame({
    'curso_id': [101, 102, 103],
    'nombre_curso': ['Introducción a Python', 'Data Science con Python', 'Machine Learning Avanzado']
})

inscripciones = pd.DataFrame({
    'curso_id': [102, 102, 101, 104],
    'fecha_inscripcion': ['2023-01-15', '2023-02-01', '2023-01-20', '2023-03-05']
})

cursos_inscripciones = pd.merge(inscripciones,cursos, on= 'curso_id', how= 'left' )
cursos_inscripciones

   curso_id fecha_inscripcion             nombre_curso
0       102        2023-01-15  Data Science con Python
1       102        2023-02-01  Data Science con Python
2       101        2023-01-20    Introducción a Python
3       104        2023-03-05                      NaN

Fusionar DataFrames con merge 3
Dispones de dos DataFrames, productos y reviews, que contienen información sobre productos y las reseñas asociadas a estos productos, respectivamente. Los DataFrames se presentan de la siguiente manera:

productos = pd.DataFrame({
    'ID': [10, 11, 12],
    'Nombre': ['Teclado', 'Mouse', 'Monitor'],
    'Marca': ['Logitech', 'Razer', 'Dell']
})
 
reviews = pd.DataFrame({
    'ID': [10, 11, 12],
    'Calificación': [5, 4, 4],
    'Comentario': ['Excelente producto', 'Buen producto', 'Satisfecho']
})
Tu tarea consiste en fusionar productos con reviews para obtener un DataFrame que combine la información de ambos (al cual debes nombrar: productos_reviews), manteniendo los índices originales de cada uno.

Utiliza los parámetros adecuados de la función merge() para realizar esta combinación. El DataFrame resultante productos_reviews debe contener las columnas de ambos DataFrames originales, permitiendo así un análisis detallado de cada producto junto con sus reseñas.

In [15]:
import pandas as pd 


productos = pd.DataFrame({
    'ID': [10, 11, 12],
    'Nombre': ['Teclado', 'Mouse', 'Monitor'],
    'Marca': ['Logitech', 'Razer', 'Dell']
})

reviews = pd.DataFrame({
    'ID': [10, 11, 12],
    'Calificación': [5, 4, 4],
    'Comentario': ['Excelente producto', 'Buen producto', 'Satisfecho']
})

productos_reviews = pd.merge(productos, reviews, left_index=True, right_index=True)
productos_reviews

   ID_x   Nombre     Marca  ID_y  Calificación          Comentario
0    10  Teclado  Logitech    10             5  Excelente producto
1    11    Mouse     Razer    11             4       Buen producto
2    12  Monitor      Dell    12             4          Satisfecho