In [2]:
import pandas as pd

In [3]:
ruta = 'Top-Películas.csv'
df = pd.read_csv(ruta)

In [4]:
df

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
...,...,...,...,...,...,...,...,...,...,...
2527,2527,998.0,The Invisible Man,James Whale,1933.0,71.0,Terror,7.6,87.0,0.00
2528,2528,998.0,The Invisible Man,James Whale,1933.0,71.0,Ciencia Ficción,7.6,87.0,0.00
2529,2529,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Acción,7.6,0.0,0.00
2530,2530,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Crimen,7.6,0.0,0.00
2531,2531,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Drama,7.6,0.0,0.00

In [ ]:
df_ordenado = df.sort_values(by='rating')
df_ordenado.head(10)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
2531,2531,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Drama,7.6,0.0,0.00
2530,2530,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Crimen,7.6,0.0,0.00
2529,2529,999.0,Cell 211,Daniel MonzÃ³n,2009.0,113.0,Acción,7.6,0.0,0.00
2528,2528,998.0,The Invisible Man,James Whale,1933.0,71.0,Ciencia Ficción,7.6,87.0,0.00
2495,2495,986.0,From Here to Eternity,Fred Zinnemann,1953.0,118.0,Guerra,7.6,85.0,30.50
2496,2496,987.0,50/50,Jonathan Levine,2011.0,100.0,Comedia,7.6,72.0,35.01
2497,2497,987.0,50/50,Jonathan Levine,2011.0,100.0,Drama,7.6,72.0,35.01
2482,2482,981.0,After Hours,Martin Scorsese,1985.0,97.0,Drama,7.6,90.0,10.60
2483,2483,982.0,Sabrina,Billy Wilder,1954.0,113.0,Comedia,7.6,72.0,0.00
2484,2484,982.0,Sabrina,Billy Wilder,1954.0,113.0,Drama,7.6,72.0,0.00

In [6]:
df_ordenado = df.sort_values(by='rating', ascending=False)
df_ordenado.head(10)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
5,5,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Drama,9.0,84.0,534.86
6,6,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Biografía,9.0,95.0,96.90
7,7,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Drama,9.0,95.0,96.90
8,8,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Historia,9.0,95.0,96.90
9,9,4.0,12 Angry Men,Sidney Lumet,1957.0,96.0,Crimen,9.0,97.0,4.36

In [7]:
df_ordenado = df.sort_values(by=['rating','recaudación(M)'] , ascending=False)
df_ordenado.head(10)

,indice_global,indice_estricto,título,director,año,duración,género,rating,metascore,recaudación(M)
0,0,0.0,The Shawshank Redemption,Frank Darabont,1994.0,142.0,Drama,9.3,82.0,28.34
1,1,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Crimen,9.2,100.0,134.97
2,2,1.0,The Godfather,Francis Ford Coppola,1972.0,175.0,Drama,9.2,100.0,134.97
3,3,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Acción,9.0,84.0,534.86
4,4,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Crimen,9.0,84.0,534.86
5,5,2.0,The Dark Knight,Christopher Nolan,2008.0,152.0,Drama,9.0,84.0,534.86
11,11,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Acción,9.0,94.0,377.85
12,12,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Aventura,9.0,94.0,377.85
13,13,5.0,The Lord of the Rings: The Return of the King,Peter Jackson,2003.0,201.0,Drama,9.0,94.0,377.85
6,6,3.0,Schindler's List,Steven Spielberg,1993.0,195.0,Biografía,9.0,95.0,96.90

In [13]:
df_agrupado = df.groupby(by='género')['rating'].mean().sort_values(ascending=False)
df_agrupado

género
Guerra             8.053191
Western            8.006250
Crimen             7.993500
Misterio           7.991262
Acción             7.987255
Ciencia Ficción    7.986567
Drama              7.980444
Aventura           7.980435
Deportes           7.980000
Film-Noir          7.977273
Biografía          7.971698
Animación          7.943902
Musical            7.943750
Romance            7.937398
Familiar           7.932692
Historia           7.931818
Fantasía           7.929508
Thriller           7.929286
Comedia            7.909910
Musica             7.909677
Terror             7.875758
Name: rating, dtype: float64

In [15]:
df_agrupado = df.groupby(by='año')['recaudación(M)'].sum().sort_values(ascending=False)
df_agrupado.head(10)

año
2014.0    8015.90
2019.0    7092.95
2010.0    6899.96
2016.0    6860.23
2015.0    6817.12
2012.0    6487.22
2009.0    6486.34
2018.0    5992.02
2008.0    5603.30
2017.0    5381.90
Name: recaudación(M), dtype: float64

Ordenar y Agrupar DataFrames en Pandas 1
Crea un DataFrame a partir del siguiente diccionario de datos de películas.

datos = {
    'titulo': ['Pelicula A', 'Pelicula B', 'Pelicula C', 'Pelicula D'],
    'año': [2001, 2000, 2005, 2010],
    'rating': [7.2, 6.5, 8.1, 7.5]
}
Luego, ordena este DataFrame por la columna 'año' en orden ascendente. Asegurate de almacenar el diccionario ordenado en una variable llamada: df_ordenado

In [17]:
datos = {
    'titulo': ['Pelicula A', 'Pelicula B', 'Pelicula C', 'Pelicula D'],
    'año': [2001, 2000, 2005, 2010],
    'rating': [7.2, 6.5, 8.1, 7.5]
}

df = pd.DataFrame(datos)
df_ordenado = df.sort_values(by='año')
df_ordenado

       titulo   año  rating
1  Pelicula B  2000     6.5
0  Pelicula A  2001     7.2
2  Pelicula C  2005     8.1
3  Pelicula D  2010     7.5

Ordenar y Agrupar DataFrames en Pandas 2
Usando el mismo DataFrame del Ejercicio anterior.

datos = {
    'titulo': ['Pelicula A', 'Pelicula B', 'Pelicula C', 'Pelicula D'],
    'año': [2001, 2000, 2005, 2010],
    'rating': [7.2, 6.5, 8.1, 7.5]
}
Ordena las películas primero por 'rating' en orden descendente y luego por 'año' en orden ascendente. Asegurate de almacenar el dataframe ordenado en una variable llamada: df_ordenado

In [ ]:
import pandas as pd
datos = {
    'titulo': ['Pelicula A', 'Pelicula B', 'Pelicula C', 'Pelicula D'],
    'año': [2001, 2000, 2005, 2010],
    'rating': [7.2, 6.5, 8.1, 7.5]
}

df = pd.DataFrame(datos)

df_ordenado = df.sort_values(by=['rating', 'año'], ascending=[False, True])

df_ordenado

       titulo   año  rating
2  Pelicula C  2005     8.1
3  Pelicula D  2010     7.5
0  Pelicula A  2001     7.2
1  Pelicula B  2000     6.5

Ordenar y Agrupar DataFrames en Pandas 3
Crea un nuevo DataFrame a partir del siguiente diccionario

datos = {
    'titulo': ['Pelicula A', 'Pelicula B', 'Pelicula C', 'Pelicula D', 'Pelicula E'],
    'género': ['Acción', 'Drama', 'Acción', 'Comedia', 'Drama'],
    'rating': [7.2, 8.5, 9.1, 6.5, 7.8]
}
Que contiene datos de películas incluyendo su género.

Luego, agrupa las películas por 'género' y calcula el promedio de 'rating' para cada género.  Asegurate de almacenar el grupo y promedio en una variable llamada: promedio_rating_por_genero

In [23]:
datos = {
    'titulo': ['Pelicula A', 'Pelicula B', 'Pelicula C', 'Pelicula D', 'Pelicula E'],
    'género': ['Acción', 'Drama', 'Acción', 'Comedia', 'Drama'],
    'rating': [7.2, 8.5, 9.1, 6.5, 7.8]}

df = pd.DataFrame(datos)

promedio_rating_por_genero = df.groupby(by='género')['rating'].mean()
promedio_rating_por_genero

género
Acción     8.15
Comedia    6.50
Drama      8.15
Name: rating, dtype: float64