# Proyecto del Día 7 - Analizador de Ventas

### Objetivo
Crear un programa en Python que analice un conjunto de **datos de ventas de una tienda**. El programa debe realizar varias operaciones de Data Science para proporcionar información valiosa sobre las ventas de la tienda.

### Consigna

1. **Lectura de Datos**: Crea un DataFrame que contenga los datos provistos en el archivo **Datos_Ventas_Tienda.csv** provisto en esta lección. El archivo incluirá información como *fecha de venta*, *categoría de producto*, *cantidad vendida* y *precio*.
2. **Fusión de Datos**: Crea un segundo DataFrame que contenga los datos del archivo **Datos_Ventas_Tienda2.csv** (también provisto en esta lección), y concaténalos para tener un solo dataFrame con toda la información.

3. **Tratamiento de Datos**: Utiliza Pandas para manipular estos datos. Deberás realizar tareas como limpieza de datos, filtrado y  transformaciones básicas.
4. **Análisis de Ventas**: Realiza análisis para responder preguntas como:
- ¿Cuál es el producto más vendido?
- ¿Cuál es el mes con más ventas?
5. **Datos Agrupados**: Agrupa los datos por categoría de producto y analiza las ventas por categoría.
6. **Guardar Resultados**: Al final, guarda el DataFrame completo (incluyendo la columna de meses) en un archivo .csv en tu ordenador.

In [1]:
import pandas as pd 
ruta_1 = pd.read_csv('Datos_Ventas_Tienda.csv')
ruta_2 = pd.read_csv('Datos_Ventas_Tienda2.csv')

In [3]:
ruta_1.columns

Index(['Fecha', 'Producto', 'Cantidad', 'Precio Unitario', 'Total Venta'], dtype='object')

In [4]:
ruta_2.columns

Index(['Fecha', 'Producto', 'Cantidad', 'Precio Unitario', 'Total Venta'], dtype='object')

In [6]:
df = pd.concat([ruta_1, ruta_2], ignore_index=True)
df.head(5)

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0  1/17/2023  Electrónic         7              200         1400
1   9/1/2023  Electrónic         8              200         1600
2  7/29/2023    Juguetes         3               30           90
3  10/4/2023   Alimentos         4               10           40
4  2/28/2023  Electrónic         6              200         1200

In [9]:
df.describe

<bound method NDFrame.describe of           Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0     1/17/2023  Electrónic         7              200         1400
1      9/1/2023  Electrónic         8              200         1600
2     7/29/2023    Juguetes         3               30           90
3     10/4/2023   Alimentos         4               10           40
4     2/28/2023  Electrónic         6              200         1200
...         ...         ...       ...              ...          ...
1045  9/11/2023    Juguetes        10               30          300
1046   1/3/2023    Juguetes        10               30          300
1047  11/7/2023   Alimentos         3               10           30
1048  8/20/2023  Electrónic         6              200         1200
1049  7/21/2023    Juguetes         3               30           90

[1050 rows x 5 columns]>

In [10]:
df.describe()

          Cantidad  Precio Unitario  Total Venta
count  1050.000000      1050.000000  1050.000000
mean      5.490476        64.428571   349.761905
std       2.882577        72.437522   473.870983
min       1.000000        10.000000    10.000000
25%       3.000000        20.000000    70.000000
50%       5.000000        30.000000   150.000000
75%       8.000000        50.000000   400.000000
max      10.000000       200.000000  2000.000000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            1050 non-null   object
 1   Producto         1050 non-null   object
 2   Cantidad         1050 non-null   int64
 3   Precio Unitario  1050 non-null   int64
 4   Total Venta      1050 non-null   int64
dtypes: int64(3), object(2)
memory usage: 41.1+ KB

In [19]:
df['Fecha'] = pd.to_datetime(df['Fecha'])
type(df['Fecha'][0])

C:\Users\juanp\AppData\Local\Temp\ipykernel_14736\2613868091.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Fecha'] = pd.to_datetime(df['Fecha'])

pandas._libs.tslibs.timestamps.Timestamp

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            1050 non-null   datetime64[ns]
 1   Producto         1050 non-null   object
 2   Cantidad         1050 non-null   int64
 3   Precio Unitario  1050 non-null   int64
 4   Total Venta      1050 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 41.1+ KB

In [21]:
conteo_nan_por_columna = df.isna().sum()
print(conteo_nan_por_columna)

Fecha              0
Producto           0
Cantidad           0
Precio Unitario    0
Total Venta        0
dtype: int64

In [23]:
df['nombre_mes'] = df['Fecha'].dt.month_name()
df.head(5)

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta nombre_mes
0 2023-01-17  Electrónic         7              200         1400    January
1 2023-09-01  Electrónic         8              200         1600  September
2 2023-07-29    Juguetes         3               30           90       July
3 2023-10-04   Alimentos         4               10           40    October
4 2023-02-28  Electrónic         6              200         1200   February

In [26]:
# Producto mas vendido 
df_producto_mas_vendido = df.groupby(by='Producto')['Cantidad'].sum().sort_values(ascending=False)
df_producto_mas_vendido

Producto
Alimentos     1262
Electrónic    1220
Ropa          1128
Juguetes      1113
Libros        1042
Name: Cantidad, dtype: int64

In [32]:
mes_mas_vemtas = df.groupby(by='nombre_mes')['Total Venta'].sum().sort_values(ascending=False)
mes_mas_vemtas

nombre_mes
August       45090
January      43030
May          39380
December     33560
June         30520
February     28410
September    27870
July         26350
October      25610
April        23210
March        23200
November     21020
Name: Total Venta, dtype: int64

In [33]:
venta_categoria = df.groupby(by='Producto')['Total Venta'].sum().sort_values(ascending=False)
venta_categoria

Producto
Electrónic    244000
Ropa           56400
Juguetes       33390
Libros         20840
Alimentos      12620
Name: Total Venta, dtype: int64

In [34]:
df.to_csv('completo_datos_venta.csv', index=False)