In [36]:
import pandas as pd

In [37]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

df = pd.DataFrame(data)

In [38]:
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    22   Valencia
3    Sara    27     Bilbao

In [39]:
df['salario'] = [30000,45000,38000,32000]
df

   Nombre  Edad     Ciudad  salario
0     Ana    25     Madrid    30000
1    Luis    30  Barcelona    45000
2  Carlos    22   Valencia    38000
3    Sara    27     Bilbao    32000

In [40]:
df['salario'] = df['salario'] +2000
df

   Nombre  Edad     Ciudad  salario
0     Ana    25     Madrid    32000
1    Luis    30  Barcelona    47000
2  Carlos    22   Valencia    40000
3    Sara    27     Bilbao    34000

In [41]:
nombres = df['Nombre']
nombres

0       Ana
1      Luis
2    Carlos
3      Sara
Name: Nombre, dtype: object

In [42]:
mayores_25 = df[df['Edad'] > 25]
mayores_25

  Nombre  Edad     Ciudad  salario
1   Luis    30  Barcelona    47000
3   Sara    27     Bilbao    34000

In [43]:
edades = df['Edad']
edades

0    25
1    30
2    22
3    27
Name: Edad, dtype: int64

In [44]:
mayores_25 = df[edades > 25]
mayores_25

  Nombre  Edad     Ciudad  salario
1   Luis    30  Barcelona    47000
3   Sara    27     Bilbao    34000

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
type(edades)

pandas.core.series.Series

In [47]:
type(mayores_25)

pandas.core.frame.DataFrame

Crea un DataFrame llamado libros_df con la siguiente información sobre libros:

Los títulos son: "El Quijote", "Cien años de soledad", "La odisea"

Los autores son "Miguel de Cervantes", "Gabriel García Márquez", "Homero"

Los años de publicación son 1605, 1967, y -800, respectivamente.



Asegúrate de utilizar las columnas Titulo, Autor y Año.

In [48]:
import pandas as pd 

libros= {'Titulo':["El Quijote", "Cien años de soledad", "La odisea"],
        'Autor':['Miguel de Cervantes', "Gabriel García Márquez", "Homero"],
        'Año':[1605, 1967, -800]}
        
libros_df = pd.DataFrame(libros)

Dado el DataFrame df con columnas Nombre, Edad y Ciudad, como se mostró en la lección, escribe un código para filtrar las filas que contienen personas de 25 años o más. Asegurate de guardar en el dataframe filtrado en una variable llamada: df_filtrado

In [49]:
# Datos proporcionados
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']}

df = pd.DataFrame(data)

df_filtrado = df[df['Edad']>= 25]

df_filtrado

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
3   Sara    27     Bilbao

Partiendo del DataFrame df mencionado anteriormente:



# Datos proporcionados
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}


Realiza las siguientes operaciones:

Crea un dataframe llamado df

Agrega una nueva columna llamada Edad_en_10_años que contenga la edad de las personas dentro de 10 años.

Modifica la columna Ciudad para que todas las ciudades estén en mayúsculas.

Crea una nueva columna Es_Mayor_de_25 que contenga valores booleanos: True si la persona tiene 25 años o más, y False en caso contrario.

In [63]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

df = pd.DataFrame(data)

df['Edad_en_10_años'] = df['Edad'] + 10
df

   Nombre  Edad     Ciudad  Edad_en_10_años
0     Ana    25     Madrid               35
1    Luis    30  Barcelona               40
2  Carlos    22   Valencia               32
3    Sara    27     Bilbao               37

In [64]:
df['Ciudad'] = df['Ciudad'].str.upper()
df

   Nombre  Edad     Ciudad  Edad_en_10_años
0     Ana    25     MADRID               35
1    Luis    30  BARCELONA               40
2  Carlos    22   VALENCIA               32
3    Sara    27     BILBAO               37

In [65]:

filtro = df[df['Edad']>= 25]
print(filtro)

  Nombre  Edad     Ciudad  Edad_en_10_años
0    Ana    25     MADRID               35
1   Luis    30  BARCELONA               40
3   Sara    27     BILBAO               37

In [66]:
df['mascara'] = df['Edad']>= 25
df

   Nombre  Edad     Ciudad  Edad_en_10_años  mascara
0     Ana    25     MADRID               35     True
1    Luis    30  BARCELONA               40     True
2  Carlos    22   VALENCIA               32    False
3    Sara    27     BILBAO               37     True